apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: openhack-services
  namespace: default
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      openhack: "true"
  namespaceSelector:
    any: true
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
