use crate::app::{App, ServiceName};
use std::fs;
use std::path::Path;

pub fn generate(app: &App, output_dir: &Path) -> Result<(), Box<dyn std::error::Error>> {
    let azure_dir = output_dir.join("infra").join("azure");
    fs::create_dir_all(&azure_dir)?;

    generate_bicep(app, &azure_dir)?;
    generate_deploy_script(app, &azure_dir)?;

    Ok(())
}

#[allow(clippy::too_many_lines)]
fn generate_bicep(app: &App, dir: &Path) -> Result<(), Box<dyn std::error::Error>> {
    let mut out = String::new();
    out.push_str("// azuredeploy.bicep — Generated by openhack-cli\n\n");

    out.push_str("param location string = '");
    out.push_str(&app.azure_location);
    out.push_str("'\nparam environment string = '");
    out.push_str(&app.environment);
    out.push_str("'\nparam projectName string = '");
    out.push_str(&app.docker_compose_project_name);
    out.push_str("'\n\n");

    out.push_str(
        "resource rg 'Microsoft.Resources/resourceGroups@2023-07-01' existing = {\n  name: '",
    );
    out.push_str(&app.azure_resource_group);
    out.push_str("'\n}\n\n");

    out.push_str("// PostgreSQL — CosmosDB for PostgreSQL or Flexible Server\n");
    out.push_str(&format!(
        "resource postgres 'Microsoft.DBforPostgreSQL/flexibleServers@2023-06-01' {{\n  name: '${{projectName}}-postgres-${{environment}}'\n  location: location\n  resourceGroup: rg.name\n  sku: {{\n    name: 'Standard_B1ms'\n    tier: 'Burstable'\n  }}\n  storage: {{\n    storageSizeGB: 32\n  }}\n  version: '16'\n  administratorLogin: '{db_user}'\n  administratorLoginPassword: '{db_pass}'\n  authConfig: {{\n    activeDirectoryAuth: 'Disabled'\n    passwordAuth: 'Enabled'\n  }}\n}}\n\nresource postgresDb 'Microsoft.DBforPostgreSQL/flexibleServers/databases@2023-06-01' = {{\n  name: '${{postgres.name}}/{db_name}'\n  properties: {{\n    charset: 'UTF8'\n    collation: 'en_US.utf8'\n  }}\n  dependsOn: [\n    postgres\n  ]\n}}\n\n",
        db_user = app.db_username,
        db_pass = app.db_password,
        db_name = app.db_name
    ));

    out.push_str("// Blob Storage\n");
    out.push_str("resource storage 'Microsoft.Storage/storageAccounts@2023-01-01' = {\n  name: '${projectName}storage${environment}'\n  location: location\n  resourceGroup: rg.name\n  sku: {\n    name: 'Standard_LRS'\n  }\n  kind: 'StorageV2'\n  properties: {\n    accessTier: 'Hot'\n  }\n}\n\n");

    out.push_str("resource blobContainer 'Microsoft.Storage/storageAccounts/blobServices/containers@2023-01-01' = {\n  name: '${storage.name}/default/media'\n  properties: {\n    publicAccess: 'Blob'\n  }\n  dependsOn: [\n    storage\n  ]\n}\n\n");

    out.push_str("// Managed Environment for Container Apps\n");
    out.push_str("resource env 'Microsoft.App/managedEnvironments@2023-05-01' = {\n  name: '${projectName}-env-${environment}'\n  location: location\n  resourceGroup: rg.name\n  properties: {\n    appLogsConfiguration: {\n      destination: 'log-analytics'\n    }\n  }\n}\n\n");

    out.push_str("// Container Apps\n");
    for &svc in &app.enabled_services {
        let name = svc.docker_name();
        let port = svc.port();

        let mut env_vars = format!(
            "        {{ name: 'DATABASE_URL', value: 'postgresql://{db_user}:{db_pass}@${{postgres.fullyQualifiedDomainName}}:5432/{db_name}' }}\n        {{ name: 'REDIS_URL', value: '{redis_url}' }}\n        {{ name: 'RUST_LOG', value: 'info' }}\n        {{ name: 'ENVIRONMENT', value: '{env}' }}\n",
            db_user = app.db_username,
            db_pass = app.db_password,
            db_name = app.db_name,
            redis_url = app.redis_url,
            env = app.environment
        );

        match svc {
            ServiceName::Auth => {
                env_vars.push_str(&format!(
                    "        {{ name: 'JWT_SECRET', value: '{}' }}\n",
                    app.jwt_secret
                ));
            }
            ServiceName::Core => {
                env_vars.push_str(&format!(
                    "        {{ name: 'JWT_SECRET', value: '{}' }}\n",
                    app.jwt_secret
                ));
            }
            ServiceName::Notify => {
                env_vars.push_str(&format!(
                    "        {{ name: 'JWT_SECRET', value: '{}' }}\n",
                    app.jwt_secret
                ));
            }
            ServiceName::Sponsors => {
                env_vars.push_str(&format!(
                    "        {{ name: 'JWT_SECRET', value: '{}' }}\n",
                    app.jwt_secret
                ));
            }
            ServiceName::Ai => {
                env_vars.push_str(&format!(
                    "        {{ name: 'LLM_PROVIDER', value: '{}' }}\n",
                    app.ai_provider
                ));
                env_vars.push_str(&format!(
                    "        {{ name: 'OPENAI_API_KEY', value: '{}' }}\n",
                    app.openai_api_key
                ));
            }
            ServiceName::Media => {
                env_vars.push_str("        { name: 'STORAGE_PROVIDER', value: 'azure' }\n");
                env_vars
                    .push_str("        { name: 'AZURE_STORAGE_ACCOUNT', value: storage.name }\n");
                env_vars.push_str("        { name: 'AZURE_STORAGE_KEY', value: listKeys(storage.id, storage.apiVersion).keys[0].value }\n");
                env_vars.push_str("        { name: 'AZURE_CONTAINER', value: 'media' }\n");
            }
            ServiceName::Gateway => {
                env_vars.push_str("        { name: 'SERVICE_PORT', value: '8000' }\n");
            }
            _ => {}
        }

        out.push_str(&format!(
            "resource {name} 'Microsoft.App/containerApps@2023-05-01' = {{\n  name: '{name}-${{environment}}'\n  location: location\n  resourceGroup: rg.name\n  properties: {{\n    managedEnvironmentId: env.id\n    configuration: {{\n      activeRevisionsMode: 'Single'\n      ingress: {{\n        external: true\n        targetPort: {port}\n        transport: 'http'\n      }}\n    }}\n    template: {{\n      revisionSuffix: '${{uniqueString(resourceGroup().id)}}'\n      containers: [\n        {{\n          name: '{name}'\n          image: '${{projectName}}/{name}:latest'\n          env: [\n{env_vars}          ]\n        }}\n      ]\n      scale: {{\n        minReplicas: 0\n        maxReplicas: 10\n      }}\n    }}\n  }}\n  dependsOn: [\n    env\n    postgres\n  ]\n}}\n\n",
            name = name,
            port = port,
            env_vars = env_vars.trim_end()
        ));
    }

    out.push_str("// Outputs\noutput 'postgresHost' {\n  value: postgres.fullyQualifiedDomainName\n}\n\noutput 'storageAccount' {\n  value: storage.name\n}\n\n");

    fs::write(dir.join("azuredeploy.bicep"), out)?;
    Ok(())
}

#[allow(clippy::too_many_lines)]
fn generate_deploy_script(app: &App, dir: &Path) -> Result<(), Box<dyn std::error::Error>> {
    let mut out = String::new();
    out.push_str(
        "#!/usr/bin/env bash\n# deploy.sh — Generated by openhack-cli\nset -euo pipefail\n\n",
    );
    out.push_str(&format!(
        "RG=\"{}\"\nLOCATION=\"{}\"\nENV=\"{}\"\nPROJECT=\"{}\"\n\n",
        app.azure_resource_group,
        app.azure_location,
        app.environment,
        app.docker_compose_project_name
    ));

    out.push_str("echo \"Deploying OpenHack to Azure Container Apps in $LOCATION ...\"\n\n");
    out.push_str("az extension add --name containerapp --yes 2>/dev/null || true\n\n");

    out.push_str("# Deploy infrastructure\naz deployment group create \\\n  --resource-group $RG \\\n  --template-file azuredeploy.bicep \\\n  --parameters location=$LOCATION environment=$ENV projectName=$PROJECT\n\n");

    for &svc in &app.enabled_services {
        let name = svc.docker_name();
        out.push_str(&format!(
            "echo \"Deploying {name} ...\"\naz containerapp up \\\n  --name {name}-$ENV \\\n  --resource-group $RG \\\n  --location $LOCATION \\\n  --environment ${{PROJECT}}-env-$ENV \\\n  --image ${{PROJECT}}/{name}:latest \\\n  --target-port {port} \\\n  --ingress external \\\n  --min-replicas 0 \\\n  --max-replicas 10 \\\n  --cpu 0.25 \\\n  --memory 0.5Gi\n\necho \"{name} deployed.\"\n\n",
            name = name,
            port = svc.port()
        ));
    }

    out.push_str("echo \"All services deployed.\"\n");

    let deploy_path = dir.join("deploy.sh");
    fs::write(&deploy_path, out)?;
    Ok(())
}
