use crate::app::{App, ServiceName};
use std::fs;
use std::path::Path;

#[allow(clippy::too_many_lines)]
pub fn generate_override(app: &App, output_dir: &Path) -> Result<(), Box<dyn std::error::Error>> {
    fs::create_dir_all(output_dir)?;

    let mut out = String::new();
    out.push_str("# docker-compose.override.yml — Generated by openhack-cli\n");
    out.push_str("# Compose profiles: core (default) + full (all services)\n\n");
    out.push_str("services:\n");

    let mut profiles = vec!["core".to_string()];
    let has_redis = app.uses_redis();
    let has_full_services = app.enabled_services.iter().any(|s| !s.is_core_service());

    if has_redis {
        profiles.push("redis".into());
    }
    if has_full_services || app.uses_minio() {
        profiles.push("full".into());
    }

    out.push_str(&format!("  # Active profiles: {}\n", profiles.join(", ")));
    out.push('\n');

    out.push_str("  # ================================\n");
    out.push_str("  # Infrastructure\n");
    out.push_str("  # ================================\n\n");

    if has_redis {
        out.push_str("  redis:\n");
        out.push_str("    profiles:\n");
        out.push_str("      - redis\n");
        out.push_str("    ports:\n");
        out.push_str(&format!(
            "      - \"{}:{}\"\n",
            app.redis_port, app.redis_port
        ));
        out.push('\n');
    }

    if app.uses_minio() {
        out.push_str("  minio:\n");
        out.push_str("    profiles:\n");
        out.push_str("      - full\n");
        out.push_str("    ports:\n");
        out.push_str("      - \"9000:9000\"\n");
        out.push_str("      - \"9001:9001\"\n");
        out.push_str("    environment:\n");
        out.push_str(&format!(
            "      MINIO_ROOT_USER: {}\n",
            app.minio_access_key
        ));
        out.push_str(&format!(
            "      MINIO_ROOT_PASSWORD: {}\n",
            app.minio_secret_key
        ));
        out.push('\n');
    }

    out.push_str("  # ================================\n");
    out.push_str("  # Application Services\n");
    out.push_str("  # ================================\n\n");

    for &svc in &app.enabled_services {
        let docker_name = svc.docker_name();
        let port = svc.port();

        out.push_str(&format!("  {}:\n", docker_name));

        if !svc.is_core_service() {
            out.push_str("    profiles:\n");
            out.push_str("      - full\n");
        }

        out.push_str("    environment:\n");

        out.push_str(&format!(
            "      DATABASE_URL: postgresql://{}:{}@pgbouncer:6432/{}\n",
            app.db_username, app.db_password, app.db_name
        ));

        if has_redis {
            out.push_str(&format!("      REDIS_URL: {}\n", app.redis_url));
        } else {
            out.push_str("      REDIS_URL: \"\"\n");
        }

        match svc {
            ServiceName::Auth => {
                out.push_str(&format!("      JWT_SECRET: {}\n", app.jwt_secret));
                out.push_str(&format!("      JWT_EXPIRY: {}\n", app.jwt_expiry));
                out.push_str(&format!(
                    "      REFRESH_TOKEN_EXPIRY: {}\n",
                    app.refresh_token_expiry
                ));
                if app.github_enabled {
                    out.push_str(&format!(
                        "      GITHUB_CLIENT_ID: {}\n",
                        app.github_client_id
                    ));
                    out.push_str(&format!(
                        "      GITHUB_CLIENT_SECRET: {}\n",
                        app.github_client_secret
                    ));
                }
                if app.google_enabled {
                    out.push_str(&format!(
                        "      GOOGLE_CLIENT_ID: {}\n",
                        app.google_client_id
                    ));
                    out.push_str(&format!(
                        "      GOOGLE_CLIENT_SECRET: {}\n",
                        app.google_client_secret
                    ));
                }
                if app.discord_oauth_enabled {
                    out.push_str(&format!(
                        "      DISCORD_CLIENT_ID: {}\n",
                        app.discord_client_id
                    ));
                    out.push_str(&format!(
                        "      DISCORD_CLIENT_SECRET: {}\n",
                        app.discord_client_secret
                    ));
                }
                out.push_str(&format!("      SERVICE_PORT: \"{}\"\n", port));
                out.push_str("      RUST_LOG: info\n");
            }
            ServiceName::Core => {
                out.push_str(&format!("      JWT_SECRET: {}\n", app.jwt_secret));
                out.push_str("      AUTH_SERVICE_URL: http://auth-svc:3001\n");
                if app.is_service_enabled(ServiceName::Media) {
                    out.push_str("      MEDIA_SERVICE_URL: http://media-svc:3010\n");
                }
                out.push_str(&format!("      SERVICE_PORT: \"{}\"\n", port));
            }
            ServiceName::Mail => {
                out.push_str(&format!("      SMTP_HOST: {}\n", app.smtp_host));
                out.push_str(&format!("      SMTP_PORT: \"{}\"\n", app.smtp_port));
                out.push_str(&format!("      MAIL_FROM: {}\n", app.mail_from));
                out.push_str(&format!("      SERVICE_PORT: \"{}\"\n", port));
                out.push_str("      RUST_LOG: info\n");
            }
            ServiceName::Judging => {
                out.push_str(&format!("      SERVICE_PORT: \"{}\"\n", port));
            }
            ServiceName::Leaderboard => {
                out.push_str(&format!("      SERVICE_PORT: \"{}\"\n", port));
                out.push_str("      RUST_LOG: info\n");
            }
            ServiceName::Notify => {
                out.push_str(&format!("      JWT_SECRET: {}\n", app.jwt_secret));
                if !app.discord_bot_token.is_empty() {
                    out.push_str(&format!(
                        "      DISCORD_WEBHOOK_URL: {}\n",
                        app.discord_bot_token
                    ));
                }
                if !app.slack_bot_token.is_empty() {
                    out.push_str(&format!("      SLACK_BOT_TOKEN: {}\n", app.slack_bot_token));
                }
                out.push_str(&format!("      SERVICE_PORT: \"{}\"\n", port));
            }
            ServiceName::Ai => {
                out.push_str(&format!("      LLM_PROVIDER: {}\n", app.ai_provider));
                if !app.openai_api_key.is_empty() {
                    out.push_str(&format!("      OPENAI_API_KEY: {}\n", app.openai_api_key));
                }
                if !app.anthropic_api_key.is_empty() {
                    out.push_str(&format!(
                        "      ANTHROPIC_API_KEY: {}\n",
                        app.anthropic_api_key
                    ));
                }
                out.push_str(&format!("      OPENAI_MODEL: {}\n", app.openai_model));
                out.push_str(&format!(
                    "      EMBEDDINGS_MODEL: {}\n",
                    app.ai_embedding_model
                ));
                out.push_str(&format!("      RAG_TOP_K: \"{}\"\n", app.ai_rag_top_k));
                out.push_str(&format!("      SERVICE_PORT: \"{}\"\n", port));
            }
            ServiceName::Analytics => {
                out.push_str(&format!("      SERVICE_PORT: \"{}\"\n", port));
            }
            ServiceName::Sponsors => {
                out.push_str(&format!("      JWT_SECRET: {}\n", app.jwt_secret));
                out.push_str(&format!("      SERVICE_PORT: \"{}\"\n", port));
            }
            ServiceName::Media => {
                out.push_str(&format!(
                    "      STORAGE_PROVIDER: {}\n",
                    app.storage_provider
                ));
                out.push_str("      STORAGE_PATH: /app/uploads\n");
                if app.uses_minio() {
                    out.push_str(&format!("      S3_ENDPOINT_URL: {}\n", app.minio_endpoint));
                    out.push_str(&format!("      S3_BUCKET_NAME: {}\n", app.minio_bucket));
                    out.push_str(&format!(
                        "      AWS_ACCESS_KEY_ID: {}\n",
                        app.minio_access_key
                    ));
                    out.push_str(&format!(
                        "      AWS_SECRET_ACCESS_KEY: {}\n",
                        app.minio_secret_key
                    ));
                } else if app.uses_s3() {
                    out.push_str(&format!(
                        "      S3_ENDPOINT_URL: https://s3.{}.amazonaws.com\n",
                        app.aws_region
                    ));
                    out.push_str(&format!("      S3_BUCKET_NAME: {}\n", app.aws_s3_bucket));
                    out.push_str(&format!(
                        "      AWS_ACCESS_KEY_ID: {}\n",
                        app.aws_access_key_id
                    ));
                    out.push_str(&format!(
                        "      AWS_SECRET_ACCESS_KEY: {}\n",
                        app.aws_secret_access_key
                    ));
                }
                out.push_str(&format!("      MAX_FILE_SIZE: \"{}\"\n", app.max_file_size));
            }
            ServiceName::Gateway => {
                out.push_str("      SERVICE_PORT: \"8000\"\n");
                out.push_str("      RUST_LOG: info\n");
            }
            ServiceName::DiscordBot => {
                out.push_str(&format!("      JWT_SECRET: {}\n", app.jwt_secret));
                out.push_str("      GATEWAY_URL: http://gateway-svc:8000\n");
                out.push_str("      SERVICE_PORT: \"3011\"\n");
                out.push_str("      RUST_LOG: info\n");
            }
        }

        out.push_str(&format!("    ports:\n      - \"{}:{}\"\n", port, port));
        out.push('\n');
    }

    out.push_str("  # ================================\n");
    out.push_str("  # API Gateway (gateway-rust)\n");
    out.push_str("  # ================================\n\n");

    out.push_str("  gateway-svc:\n");
    out.push_str("    ports:\n");
    out.push_str("      - \"8000:8000\"\n");

    let override_path = output_dir.join("docker-compose.override.yml");
    fs::write(&override_path, out)?;
    Ok(())
}
