use crate::app::{App, ServiceName};
use std::fs;
use std::path::Path;

#[allow(clippy::too_many_lines)]
pub fn generate(app: &App, output_dir: &Path) -> Result<(), Box<dyn std::error::Error>> {
    fs::create_dir_all(output_dir)?;

    let mut out = String::new();

    out.push_str("# OpenHack Configuration\n");
    out.push_str("# Generated by openhack-cli — edit values as needed\n\n");

    out.push_str(
        "# =============================================================================\n",
    );
    out.push_str("# CORE CONFIGURATION\n");
    out.push_str(
        "# =============================================================================\n\n",
    );

    out.push_str(&format!("OPENHACK_NAME=\"{}\"\n", app.name));
    out.push_str(&format!("OPENHACK_DOMAIN={}\n", app.domain));
    out.push_str(&format!("OPENHACK_SECRET={}\n", app.secret));
    out.push_str(&format!("TIMEZONE={}\n", app.timezone));
    out.push('\n');
    out.push_str(&format!("ENVIRONMENT={}\n", app.environment));
    out.push_str(&format!("LOG_LEVEL={}\n", app.log_level));
    out.push_str(&format!("DEBUG={}\n", app.debug));

    out.push_str(
        "\n# =============================================================================\n",
    );
    out.push_str("# DATABASE CONFIGURATION\n");
    out.push_str(
        "# =============================================================================\n\n",
    );

    out.push_str(&format!("DATABASE_URL={}\n", app.database_url()));
    out.push_str(&format!("POSTGRES_USER={}\n", app.db_username));
    out.push_str(&format!("POSTGRES_PASSWORD={}\n", app.db_password));
    out.push_str(&format!("POSTGRES_DB={}\n", app.db_name));
    out.push_str(&format!("POSTGRES_HOST={}\n", app.db_host));
    out.push_str(&format!("POSTGRES_PORT={}\n", app.db_port));
    out.push('\n');
    out.push_str(&format!("DB_POOL_MIN={}\n", app.db_pool_min));
    out.push_str(&format!("DB_POOL_MAX={}\n", app.db_pool_max));
    out.push_str(&format!("DB_POOL_TIMEOUT={}\n", app.db_pool_timeout));

    out.push_str(
        "\n# =============================================================================\n",
    );
    out.push_str("# REDIS CONFIGURATION\n");
    out.push_str(
        "# =============================================================================\n\n",
    );

    if app.uses_redis() {
        out.push_str(&format!("REDIS_URL={}\n", app.redis_url));
        out.push_str(&format!("REDIS_HOST={}\n", app.redis_host));
        out.push_str(&format!("REDIS_PORT={}\n", app.redis_port));
        out.push_str(&format!("REDIS_PASSWORD={}\n", app.redis_password));
        out.push('\n');
        out.push_str(&format!("REDIS_POOL_MIN={}\n", app.redis_pool_min));
        out.push_str(&format!("REDIS_POOL_MAX={}\n", app.redis_pool_max));
    } else {
        out.push_str("# REDIS_URL=\n");
        out.push_str("# REDIS_HOST=redis\n");
        out.push_str("# REDIS_PORT=6379\n");
        out.push_str("# REDIS_PASSWORD=\n");
        out.push('\n');
        out.push_str("# REDIS_POOL_MIN=5\n");
        out.push_str("# REDIS_POOL_MAX=20\n");
    }

    out.push_str(
        "\n# =============================================================================\n",
    );
    out.push_str("# AUTH SERVICE CONFIGURATION\n");
    out.push_str(
        "# =============================================================================\n\n",
    );

    out.push_str(&format!("AUTH_JWT_SECRET={}\n", app.jwt_secret));
    out.push_str(&format!("AUTH_JWT_EXPIRY={}\n", app.jwt_expiry));
    out.push_str(&format!(
        "AUTH_REFRESH_TOKEN_EXPIRY={}\n",
        app.refresh_token_expiry
    ));
    out.push_str(&format!("AUTH_JWT_ISSUER={}\n", app.jwt_issuer));
    out.push('\n');
    out.push_str(&format!(
        "AUTH_PASSWORD_MIN_LENGTH={}\n",
        app.password_min_length
    ));
    out.push_str(&format!(
        "AUTH_PASSWORD_REQUIRE_UPPERCASE={}\n",
        app.password_require_uppercase
    ));
    out.push_str(&format!(
        "AUTH_PASSWORD_REQUIRE_LOWERCASE={}\n",
        app.password_require_lowercase
    ));
    out.push_str(&format!(
        "AUTH_PASSWORD_REQUIRE_NUMBERS={}\n",
        app.password_require_numbers
    ));
    out.push_str(&format!(
        "AUTH_PASSWORD_REQUIRE_SPECIAL={}\n",
        app.password_require_special
    ));
    out.push('\n');
    out.push_str(&format!("AUTH_SESSION_TIMEOUT={}\n", app.session_timeout));
    out.push_str(&format!(
        "AUTH_SESSION_COOKIE_SECURE={}\n",
        app.session_cookie_secure
    ));
    out.push_str(&format!(
        "AUTH_SESSION_COOKIE_HTTPONLY={}\n",
        app.session_cookie_httponly
    ));
    out.push_str(&format!(
        "AUTH_SESSION_COOKIE_SAMESITE={}\n",
        app.session_cookie_samesite
    ));
    out.push('\n');
    out.push_str(&format!(
        "AUTH_RATE_LIMIT_ENABLED={}\n",
        app.auth_rate_limit_enabled
    ));
    out.push_str(&format!(
        "AUTH_RATE_LIMIT_MAX_REQUESTS={}\n",
        app.auth_rate_limit_max
    ));
    out.push_str(&format!(
        "AUTH_RATE_LIMIT_WINDOW_MS={}\n",
        app.auth_rate_limit_window_ms
    ));

    out.push_str(
        "\n# =============================================================================\n",
    );
    out.push_str("# OAUTH PROVIDERS\n");
    out.push_str(
        "# =============================================================================\n\n",
    );

    if app.github_enabled {
        out.push_str("GITHUB_ENABLED=true\n");
        out.push_str(&format!("GITHUB_CLIENT_ID={}\n", app.github_client_id));
        out.push_str(&format!(
            "GITHUB_CLIENT_SECRET={}\n",
            app.github_client_secret
        ));
        out.push_str(&format!(
            "GITHUB_CALLBACK_URL={}/api/auth/oauth/github/callback\n",
            app.domain
        ));
    } else {
        out.push_str("# GITHUB_ENABLED=false\n");
        out.push_str("# GITHUB_CLIENT_ID=\n");
        out.push_str("# GITHUB_CLIENT_SECRET=\n");
        out.push_str("# GITHUB_CALLBACK_URL=\n");
    }

    if app.google_enabled {
        out.push_str("\nGOOGLE_ENABLED=true\n");
        out.push_str(&format!("GOOGLE_CLIENT_ID={}\n", app.google_client_id));
        out.push_str(&format!(
            "GOOGLE_CLIENT_SECRET={}\n",
            app.google_client_secret
        ));
        out.push_str(&format!(
            "GOOGLE_CALLBACK_URL={}/api/auth/oauth/google/callback\n",
            app.domain
        ));
    } else {
        out.push_str("\n# GOOGLE_ENABLED=false\n");
        out.push_str("# GOOGLE_CLIENT_ID=\n");
        out.push_str("# GOOGLE_CLIENT_SECRET=\n");
        out.push_str("# GOOGLE_CALLBACK_URL=\n");
    }

    if app.discord_oauth_enabled {
        out.push_str("\nDISCORD_ENABLED=true\n");
        out.push_str(&format!("DISCORD_CLIENT_ID={}\n", app.discord_client_id));
        out.push_str(&format!(
            "DISCORD_CLIENT_SECRET={}\n",
            app.discord_client_secret
        ));
        out.push_str(&format!(
            "DISCORD_CALLBACK_URL={}/api/auth/oauth/discord/callback\n",
            app.domain
        ));
    } else {
        out.push_str("\n# DISCORD_ENABLED=false\n");
        out.push_str("# DISCORD_CLIENT_ID=\n");
        out.push_str("# DISCORD_CLIENT_SECRET=\n");
        out.push_str("# DISCORD_CALLBACK_URL=\n");
    }

    out.push_str(
        "\n# =============================================================================\n",
    );
    out.push_str("# MFA CONFIGURATION\n");
    out.push_str(
        "# =============================================================================\n\n",
    );

    out.push_str(&format!("MFA_TOTP_ENABLED={}\n", app.mfa_totp_enabled));
    out.push_str(&format!("MFA_TOTP_ISSUER={}\n", app.mfa_totp_issuer));
    out.push_str("MFA_TOTP_DIGITS=6\n");
    out.push_str("MFA_TOTP_PERIOD=30\n");
    out.push('\n');
    if app.mfa_sms_enabled {
        out.push_str("MFA_SMS_ENABLED=true\n");
        out.push_str(&format!("TWILIO_ACCOUNT_SID={}\n", app.twilio_account_sid));
        out.push_str(&format!("TWILIO_AUTH_TOKEN={}\n", app.twilio_auth_token));
        out.push_str(&format!(
            "TWILIO_PHONE_NUMBER={}\n",
            app.twilio_phone_number
        ));
    } else {
        out.push_str("# MFA_SMS_ENABLED=false\n");
        out.push_str("# TWILIO_ACCOUNT_SID=\n");
        out.push_str("# TWILIO_AUTH_TOKEN=\n");
        out.push_str("# TWILIO_PHONE_NUMBER=\n");
    }

    if app.is_service_enabled(ServiceName::Mail) {
        out.push_str(
            "\n# =============================================================================\n",
        );
        out.push_str("# MAIL SERVICE CONFIGURATION\n");
        out.push_str(
            "# =============================================================================\n\n",
        );

        out.push_str(&format!("MAIL_PROVIDER={}\n", app.mail_provider));
        out.push_str(&format!("MAIL_FROM={}\n", app.mail_from));
        out.push_str(&format!("MAIL_FROM_NAME={}\n", app.mail_from_name));
        out.push('\n');
        out.push_str(&format!("SMTP_HOST={}\n", app.smtp_host));
        out.push_str(&format!("SMTP_PORT={}\n", app.smtp_port));
        out.push_str(&format!("SMTP_USER={}\n", app.smtp_user));
        out.push_str(&format!("SMTP_PASSWORD={}\n", app.smtp_password));
        out.push_str(&format!("SMTP_TLS={}\n", app.smtp_tls));
        out.push_str(&format!(
            "SMTP_REJECT_UNAUTHORIZED={}\n",
            app.smtp_reject_unauthorized
        ));
        out.push('\n');
        if app.mail_provider == "sendgrid" {
            out.push_str(&format!("SENDGRID_API_KEY={}\n", app.sendgrid_api_key));
        } else {
            out.push_str("# SENDGRID_API_KEY=\n");
        }
        if app.mail_provider == "ses" {
            out.push_str(&format!("AWS_SES_REGION={}\n", app.aws_ses_region));
            out.push_str(&format!("AWS_ACCESS_KEY_ID={}\n", app.aws_access_key_id));
            out.push_str(&format!(
                "AWS_SECRET_ACCESS_KEY={}\n",
                app.aws_secret_access_key
            ));
        } else {
            out.push_str("# AWS_SES_REGION=us-east-1\n");
            out.push_str("# AWS_ACCESS_KEY_ID=\n");
            out.push_str("# AWS_SECRET_ACCESS_KEY=\n");
        }
        out.push('\n');
        out.push_str(&format!(
            "MAIL_RATE_LIMIT_ENABLED={}\n",
            app.mail_rate_limit_enabled
        ));
        out.push_str(&format!(
            "MAIL_RATE_LIMIT_MAX_PER_HOUR={}\n",
            app.mail_rate_limit_max_per_hour
        ));
    } else {
        out.push_str(
            "\n# =============================================================================\n",
        );
        out.push_str("# MAIL SERVICE CONFIGURATION (disabled)\n");
        out.push_str(
            "# =============================================================================\n\n",
        );
        out.push_str("# MAIL_PROVIDER=smtp\n");
        out.push_str("# MAIL_FROM=noreply@${OPENHACK_DOMAIN}\n");
        out.push_str("# MAIL_FROM_NAME=${OPENHACK_NAME}\n");
    }

    if app.is_service_enabled(ServiceName::Notify) {
        out.push_str(
            "\n# =============================================================================\n",
        );
        out.push_str("# NOTIFICATION SERVICE CONFIGURATION\n");
        out.push_str(
            "# =============================================================================\n\n",
        );

        out.push_str(&format!("DISCORD_BOT_TOKEN={}\n", app.discord_bot_token));
        out.push_str(&format!("DISCORD_GUILD_ID={}\n", app.discord_guild_id));
        out.push_str(&format!("SLACK_BOT_TOKEN={}\n", app.slack_bot_token));
        out.push_str(&format!(
            "SLACK_SIGNING_SECRET={}\n",
            app.slack_signing_secret
        ));
        out.push('\n');
        out.push_str(&format!("WEBHOOK_SECRET={}\n", app.webhook_secret));
        out.push_str(&format!(
            "WEBHOOK_RETRY_COUNT={}\n",
            app.webhook_retry_count
        ));
        out.push_str(&format!("WEBHOOK_TIMEOUT={}\n", app.webhook_timeout_ms));
    } else {
        out.push_str(
            "\n# =============================================================================\n",
        );
        out.push_str("# NOTIFICATION SERVICE CONFIGURATION (disabled)\n");
        out.push_str(
            "# =============================================================================\n\n",
        );
        out.push_str("# DISCORD_BOT_TOKEN=\n");
        out.push_str("# DISCORD_GUILD_ID=\n");
        out.push_str("# SLACK_BOT_TOKEN=\n");
        out.push_str("# SLACK_SIGNING_SECRET=\n");
    }

    if app.is_service_enabled(ServiceName::Ai) {
        out.push_str(
            "\n# =============================================================================\n",
        );
        out.push_str("# AI SERVICE CONFIGURATION\n");
        out.push_str(
            "# =============================================================================\n\n",
        );

        out.push_str(&format!("AI_PROVIDER={}\n", app.ai_provider));
        out.push_str(&format!("AI_ENABLED={}\n", app.ai_enabled));
        out.push('\n');
        if app.ai_provider == "openai" || !app.openai_api_key.is_empty() {
            out.push_str(&format!("OPENAI_API_KEY={}\n", app.openai_api_key));
            out.push_str(&format!("OPENAI_MODEL={}\n", app.openai_model));
            out.push_str(&format!("OPENAI_MAX_TOKENS={}\n", app.openai_max_tokens));
            out.push_str(&format!("OPENAI_TEMPERATURE={}\n", app.openai_temperature));
        } else {
            out.push_str("# OPENAI_API_KEY=\n");
            out.push_str("# OPENAI_MODEL=gpt-4-turbo\n");
        }
        if app.ai_provider == "anthropic" || !app.anthropic_api_key.is_empty() {
            out.push_str(&format!("ANTHROPIC_API_KEY={}\n", app.anthropic_api_key));
            out.push_str(&format!("ANTHROPIC_MODEL={}\n", app.anthropic_model));
        } else {
            out.push_str("# ANTHROPIC_API_KEY=\n");
            out.push_str("# ANTHROPIC_MODEL=\n");
        }
        if app.ollama_enabled {
            out.push_str("\nOLLAMA_ENABLED=true\n");
            out.push_str(&format!("OLLAMA_BASE_URL={}\n", app.ollama_base_url));
            out.push_str(&format!("OLLAMA_MODEL={}\n", app.ollama_model));
        } else {
            out.push_str("\n# OLLAMA_ENABLED=false\n");
            out.push_str("# OLLAMA_BASE_URL=http://localhost:11434\n");
        }
        if !app.azure_openai_endpoint.is_empty() {
            out.push_str(&format!(
                "\nAZURE_OPENAI_ENDPOINT={}\n",
                app.azure_openai_endpoint
            ));
            out.push_str(&format!(
                "AZURE_OPENAI_API_KEY={}\n",
                app.azure_openai_api_key
            ));
            out.push_str(&format!(
                "AZURE_OPENAI_DEPLOYMENT={}\n",
                app.azure_openai_deployment
            ));
            out.push_str(&format!(
                "AZURE_OPENAI_API_VERSION={}\n",
                app.azure_openai_api_version
            ));
        } else {
            out.push_str("\n# AZURE_OPENAI_ENDPOINT=\n");
        }
        out.push('\n');
        out.push_str(&format!("AI_FEATURE_CHAT={}\n", app.ai_feature_chat));
        out.push_str(&format!(
            "AI_FEATURE_IDEA_GENERATOR={}\n",
            app.ai_feature_idea_generator
        ));
        out.push_str(&format!(
            "AI_FEATURE_TEAM_MATCHER={}\n",
            app.ai_feature_team_matcher
        ));
        out.push_str(&format!(
            "AI_FEATURE_CODE_REVIEW={}\n",
            app.ai_feature_code_review
        ));
        out.push_str(&format!(
            "AI_FEATURE_ORGANIZER_INSIGHTS={}\n",
            app.ai_feature_organizer_insights
        ));
        out.push('\n');
        out.push_str(&format!("AI_RAG_ENABLED={}\n", app.ai_rag_enabled));
        out.push_str(&format!("AI_RAG_TOP_K={}\n", app.ai_rag_top_k));
        out.push_str(&format!("AI_EMBEDDING_MODEL={}\n", app.ai_embedding_model));
    } else {
        out.push_str(
            "\n# =============================================================================\n",
        );
        out.push_str("# AI SERVICE CONFIGURATION (disabled)\n");
        out.push_str(
            "# =============================================================================\n\n",
        );
        out.push_str("# AI_ENABLED=false\n");
    }

    out.push_str(
        "\n# =============================================================================\n",
    );
    out.push_str("# STORAGE CONFIGURATION\n");
    out.push_str(
        "# =============================================================================\n\n",
    );

    out.push_str(&format!("STORAGE_PROVIDER={}\n", app.storage_provider));
    out.push('\n');
    if app.storage_provider == "local" {
        out.push_str(&format!("LOCAL_STORAGE_PATH={}\n", app.local_storage_path));
        out.push_str(&format!(
            "LOCAL_STORAGE_MAX_SIZE={}\n",
            app.local_storage_max_size
        ));
    } else {
        out.push_str("# LOCAL_STORAGE_PATH=/var/lib/openhack/media\n");
    }
    if app.uses_minio() {
        out.push_str(&format!("MINIO_ENDPOINT={}\n", app.minio_endpoint));
        out.push_str(&format!("MINIO_BUCKET={}\n", app.minio_bucket));
        out.push_str(&format!("MINIO_ACCESS_KEY={}\n", app.minio_access_key));
        out.push_str(&format!("MINIO_SECRET_KEY={}\n", app.minio_secret_key));
        out.push_str(&format!("MINIO_USE_SSL={}\n", app.minio_use_ssl));
    } else {
        out.push_str("# MINIO_ENDPOINT=http://minio:9000\n");
    }
    if app.uses_s3() {
        out.push_str(&format!("AWS_REGION={}\n", app.aws_region));
        out.push_str(&format!("AWS_S3_BUCKET={}\n", app.aws_s3_bucket));
        out.push_str(&format!("AWS_ACCESS_KEY_ID={}\n", app.aws_access_key_id));
        out.push_str(&format!(
            "AWS_SECRET_ACCESS_KEY={}\n",
            app.aws_secret_access_key
        ));
        out.push_str(&format!("S3_USE_PATH_STYLE={}\n", app.s3_use_path_style));
    } else if app.storage_provider != "minio" {
        out.push_str("# AWS_REGION=us-east-1\n");
        out.push_str("# AWS_S3_BUCKET=openhack-media\n");
    }
    if app.storage_provider == "gcs" {
        out.push_str(&format!("GCS_BUCKET={}\n", app.gcs_bucket));
        out.push_str(&format!("GCS_CREDENTIALS={}\n", app.gcs_credentials));
    } else {
        out.push_str("# GCS_BUCKET=\n");
    }
    if app.storage_provider == "azure" {
        out.push_str(&format!(
            "AZURE_STORAGE_ACCOUNT={}\n",
            app.azure_storage_account
        ));
        out.push_str(&format!("AZURE_STORAGE_KEY={}\n", app.azure_storage_key));
        out.push_str(&format!("AZURE_CONTAINER={}\n", app.azure_container));
    } else {
        out.push_str("# AZURE_STORAGE_ACCOUNT=\n");
    }
    out.push('\n');
    out.push_str(&format!("MAX_FILE_SIZE={}\n", app.max_file_size));
    out.push_str(&format!("MAX_IMAGE_SIZE={}\n", app.max_image_size));
    out.push_str(&format!("MAX_VIDEO_SIZE={}\n", app.max_video_size));

    out.push_str(
        "\n# =============================================================================\n",
    );
    out.push_str("# FRONTEND CONFIGURATION\n");
    out.push_str(
        "# =============================================================================\n\n",
    );

    out.push_str(&format!(
        "NEXT_PUBLIC_API_URL={}\n",
        app.next_public_api_url
    ));
    out.push_str(&format!("NEXT_PUBLIC_WS_URL={}\n", app.next_public_ws_url));
    out.push_str(&format!(
        "NEXT_PUBLIC_APP_NAME={}\n",
        app.next_public_app_name
    ));
    out.push('\n');
    out.push_str(&format!(
        "NEXT_PUBLIC_FEATURE_TEAMS={}\n",
        app.feature_teams
    ));
    out.push_str(&format!(
        "NEXT_PUBLIC_FEATURE_PROJECTS={}\n",
        app.feature_projects
    ));
    out.push_str(&format!(
        "NEXT_PUBLIC_FEATURE_JUDGING={}\n",
        app.feature_judging
    ));
    out.push_str(&format!(
        "NEXT_PUBLIC_FEATURE_VOTING={}\n",
        app.feature_voting
    ));
    out.push_str(&format!(
        "NEXT_PUBLIC_FEATURE_SPONSORS={}\n",
        app.feature_sponsors
    ));
    out.push_str(&format!("NEXT_PUBLIC_FEATURE_AI={}\n", app.ai_enabled));

    out.push_str(
        "\n# =============================================================================\n",
    );
    out.push_str("# GATEWAY CONFIGURATION\n");
    out.push_str(
        "# =============================================================================\n\n",
    );

    out.push_str(&format!("GATEWAY_URL={}\n", app.gateway_url));
    out.push('\n');
    out.push_str(&format!(
        "GATEWAY_RATE_LIMIT_AUTH={}\n",
        app.gateway_rate_limit_auth
    ));
    out.push_str(&format!(
        "GATEWAY_RATE_LIMIT_CORE={}\n",
        app.gateway_rate_limit_core
    ));
    out.push_str(&format!(
        "GATEWAY_RATE_LIMIT_JUDGING={}\n",
        app.gateway_rate_limit_judging
    ));
    out.push_str(&format!(
        "GATEWAY_RATE_LIMIT_MAIL={}\n",
        app.gateway_rate_limit_mail
    ));
    out.push_str(&format!(
        "GATEWAY_RATE_LIMIT_NOTIFY={}\n",
        app.gateway_rate_limit_notify
    ));
    out.push_str(&format!(
        "GATEWAY_RATE_LIMIT_AI={}\n",
        app.gateway_rate_limit_ai
    ));
    out.push('\n');
    out.push_str(&format!("CORS_ENABLED={}\n", app.cors_enabled));
    out.push_str(&format!("CORS_ORIGINS={}\n", app.cors_origins));
    out.push_str(&format!("CORS_CREDENTIALS={}\n", app.cors_credentials));
    out.push_str(&format!("CORS_MAX_AGE={}\n", app.cors_max_age));

    out.push_str(
        "\n# =============================================================================\n",
    );
    out.push_str("# MONITORING CONFIGURATION\n");
    out.push_str(
        "# =============================================================================\n\n",
    );

    out.push_str(&format!("PROMETHEUS_ENABLED={}\n", app.prometheus_enabled));
    out.push_str(&format!("PROMETHEUS_PORT={}\n", app.prometheus_port));
    out.push_str(&format!("GRAFANA_ENABLED={}\n", app.grafana_enabled));
    out.push_str(&format!(
        "GRAFANA_ADMIN_PASSWORD={}\n",
        app.grafana_admin_password
    ));
    out.push_str(&format!(
        "ALERTMANAGER_ENABLED={}\n",
        app.alertmanager_enabled
    ));
    out.push('\n');
    out.push_str(&format!("OTEL_ENABLED={}\n", app.otel_enabled));
    out.push_str(&format!(
        "OTEL_EXPORTER_OTLP_ENDPOINT={}\n",
        app.otel_endpoint
    ));
    out.push_str(&format!("OTEL_SERVICE_NAME={}\n", app.otel_service_name));

    out.push_str(
        "\n# =============================================================================\n",
    );
    out.push_str("# BACKUP CONFIGURATION\n");
    out.push_str(
        "# =============================================================================\n\n",
    );

    out.push_str(&format!("BACKUP_SCHEDULE={}\n", app.backup_schedule));
    out.push_str(&format!(
        "BACKUP_RETENTION_DAILY={}\n",
        app.backup_retention_daily
    ));
    out.push_str(&format!(
        "BACKUP_RETENTION_WEEKLY={}\n",
        app.backup_retention_weekly
    ));
    out.push_str(&format!(
        "BACKUP_RETENTION_MONTHLY={}\n",
        app.backup_retention_monthly
    ));
    out.push('\n');
    out.push_str(&format!("BACKUP_DESTINATION={}\n", app.backup_destination));
    out.push_str(&format!("BACKUP_S3_BUCKET={}\n", app.backup_s3_bucket));
    out.push_str(&format!("BACKUP_S3_REGION={}\n", app.backup_s3_region));

    out.push_str(
        "\n# =============================================================================\n",
    );
    out.push_str("# SECURITY CONFIGURATION\n");
    out.push_str(
        "# =============================================================================\n\n",
    );

    out.push_str(&format!("HTTPS_ENABLED={}\n", app.https_enabled));
    out.push_str(&format!("TLS_CERT_PATH={}\n", app.tls_cert_path));
    out.push_str(&format!("TLS_KEY_PATH={}\n", app.tls_key_path));
    out.push('\n');
    out.push_str(&format!(
        "SECURITY_HSTS_ENABLED={}\n",
        app.security_hsts_enabled
    ));
    out.push_str(&format!(
        "SECURITY_HSTS_MAX_AGE={}\n",
        app.security_hsts_max_age
    ));
    out.push_str(&format!(
        "SECURITY_FRAME_OPTIONS={}\n",
        app.security_frame_options
    ));
    out.push_str(&format!(
        "SECURITY_CONTENT_TYPE_NOSNIFF={}\n",
        app.security_content_type_nosniff
    ));
    out.push('\n');
    out.push_str(&format!("CSP_ENABLED={}\n", app.csp_enabled));
    out.push_str(&format!("CSP_DEFAULT_SRC={}\n", app.csp_default_src));
    out.push_str(&format!("CSP_SCRIPT_SRC={}\n", app.csp_script_src));
    out.push_str(&format!("CSP_STYLE_SRC={}\n", app.csp_style_src));

    out.push_str(
        "\n# =============================================================================\n",
    );
    out.push_str("# MULTI-TENANCY (Optional)\n");
    out.push_str(
        "# =============================================================================\n\n",
    );

    out.push_str(&format!(
        "MULTI_TENANCY_ENABLED={}\n",
        app.multi_tenancy_enabled
    ));
    out.push_str(&format!("TENANCY_MODEL={}\n", app.tenancy_model));
    out.push_str(&format!("DEFAULT_TENANT={}\n", app.default_tenant));

    out.push_str(
        "\n# =============================================================================\n",
    );
    out.push_str("# DEVELOPMENT ONLY\n");
    out.push_str(
        "# =============================================================================\n\n",
    );

    out.push_str(&format!("DEV_HOT_RELOAD={}\n", app.dev_hot_reload));
    out.push_str(&format!("DEV_WATCH_FILES={}\n", app.dev_watch_files));
    out.push_str(&format!(
        "DEV_ENABLE_PROFILING={}\n",
        app.dev_enable_profiling
    ));
    out.push_str(&format!(
        "DEV_ENABLE_QUERY_LOGGING={}\n",
        app.dev_enable_query_logging
    ));
    out.push_str(&format!("DEV_ENABLE_SWAGGER={}\n", app.dev_enable_swagger));
    out.push_str(&format!("DEV_SEED_DATA={}\n", app.dev_seed_data));
    out.push_str(&format!("DEV_TEST_USERS={}\n", app.dev_test_users));

    out.push_str(
        "\n# =============================================================================\n",
    );
    out.push_str("# DEPLOYMENT SPECIFIC\n");
    out.push_str(
        "# =============================================================================\n\n",
    );

    out.push_str(&format!(
        "KUBERNETES_NAMESPACE={}\n",
        app.kubernetes_namespace
    ));
    out.push_str(&format!(
        "DOCKER_COMPOSE_PROJECT_NAME={}\n",
        app.docker_compose_project_name
    ));
    out.push_str(&format!(
        "HEALTH_CHECK_INTERVAL={}\n",
        app.health_check_interval
    ));
    out.push_str(&format!(
        "HEALTH_CHECK_TIMEOUT={}\n",
        app.health_check_timeout
    ));

    out.push('\n');

    let env_path = output_dir.join(".env");
    fs::write(&env_path, out)?;
    Ok(())
}
