use crate::app::{App, ServiceName};
use std::fs;
use std::path::Path;

pub fn generate(app: &App, output_dir: &Path) -> Result<(), Box<dyn std::error::Error>> {
    let gcp_dir = output_dir.join("infra").join("gcp");
    fs::create_dir_all(&gcp_dir)?;

    generate_cloudbuild(app, &gcp_dir)?;
    generate_deploy_script(app, &gcp_dir)?;
    generate_main_tf(app, &gcp_dir)?;

    Ok(())
}

#[allow(clippy::too_many_lines)]
fn generate_cloudbuild(app: &App, dir: &Path) -> Result<(), Box<dyn std::error::Error>> {
    let mut out = String::new();
    out.push_str("# cloudbuild.yaml — Generated by openhack-cli\n\n");
    out.push_str("steps:\n");

    for &svc in &app.enabled_services {
        let name = svc.docker_name();
        out.push_str(&format!(
            "  - name: gcr.io/cloud-builders/docker\n    args:\n      - build\n      - -t\n      - gcr.io/$PROJECT_ID/{name}:$COMMIT_SHA\n      - -f\n      - services/{name}/Dockerfile\n      - services/{name}\n    id: build-{name}\n\n",
            name = name
        ));
    }

    out.push_str("  # Push images\n");
    for &svc in &app.enabled_services {
        let name = svc.docker_name();
        out.push_str(&format!(
            "  - name: gcr.io/cloud-builders/docker\n    args:\n      - push\n      - gcr.io/$PROJECT_ID/{name}:$COMMIT_SHA\n    id: push-{name}\n    waitFor:\n      - build-{name}\n\n",
            name = name
        ));
    }

    out.push_str("images:\n");
    for &svc in &app.enabled_services {
        let name = svc.docker_name();
        out.push_str(&format!("  - gcr.io/$PROJECT_ID/{}:$COMMIT_SHA\n", name));
    }
    out.push_str("\noptions:\n  logging: CLOUD_LOGGING_ONLY\n  machineType: E2_HIGHCPU_8\n");

    fs::write(dir.join("cloudbuild.yaml"), out)?;
    Ok(())
}

#[allow(clippy::too_many_lines)]
fn generate_deploy_script(app: &App, dir: &Path) -> Result<(), Box<dyn std::error::Error>> {
    let mut out = String::new();
    out.push_str(
        "#!/usr/bin/env bash\n# deploy.sh — Generated by openhack-cli\nset -euo pipefail\n\n",
    );
    out.push_str(&format!(
        "PROJECT_ID=\"{}\"\nREGION=\"{}\"\nIMAGE_TAG=\"${{COMMIT_SHA:-latest}}\"\n\n",
        app.gcp_project_id, app.gcp_region
    ));
    out.push_str("echo \"Deploying OpenHack to GCP Cloud Run in $REGION ...\"\n\n");

    for &svc in &app.enabled_services {
        let name = svc.docker_name();
        let port = svc.port();
        out.push_str(&format!(
            "echo \"Deploying {name} ...\"\ngcloud run deploy {name} \\\n  --image gcr.io/$PROJECT_ID/{name}:$IMAGE_TAG \\\n  --region $REGION \\\n  --platform managed \\\n  --port {port} \\\n  --min-instances 0 \\\n  --max-instances 10 \\\n  --memory 256Mi \\\n  --cpu 1 \\\n  --set-env-vars \"DATABASE_URL=postgresql://{db_user}:{db_pass}@/openhack?host=/cloudsql/$PROJECT_ID:$REGION:$(terraform output -raw cloud_sql_instance_name)\" \\\n  --set-env-vars \"REDIS_URL={redis_url}\" \\\n  --set-env-vars \"RUST_LOG=info\" \\\n  --set-env-vars \"ENVIRONMENT={env}\" \\\n  --allow-unauthenticated\n\necho \"{name} deployed.\"\n\n",
            name = name,
            port = port,
            db_user = app.db_username,
            db_pass = app.db_password,
            redis_url = app.redis_url,
            env = app.environment,
        ));
    }

    out.push_str("echo \"All services deployed.\"\n");

    let deploy_path = dir.join("deploy.sh");
    fs::write(&deploy_path, out)?;
    Ok(())
}

#[allow(clippy::too_many_lines)]
fn generate_main_tf(app: &App, dir: &Path) -> Result<(), Box<dyn std::error::Error>> {
    let mut out = String::new();
    out.push_str("# main.tf — Generated by openhack-cli\n\n");

    out.push_str("terraform {\n  required_providers {\n    google = {\n      source  = \"hashicorp/google\"\n      version = \"~> 5.0\"\n    }\n  }\n}\n\n");

    out.push_str(&format!(
        "provider \"google\" {{\n  project = \"{project}\"\n  region  = \"{region}\"\n}}\n\n",
        project = app.gcp_project_id,
        region = app.gcp_region
    ));

    out.push_str(&format!(
        "# Cloud SQL — PostgreSQL\nresource \"google_sql_database_instance\" \"openhack\" {{\n  name             = \"openhack-{env}\"\n  database_version = \"POSTGRES_16\"\n  region           = \"{region}\"\n  settings {{\n    tier = \"db-f1-micro\"\n    disk_size = 10\n    disk_type = \"PD_SSD\"\n  }}\n  deletion_protection = false\n}}\n\n",
        env = app.environment,
        region = app.gcp_region
    ));

    out.push_str(&format!(
        "resource \"google_sql_database\" \"openhack\" {{\n  name     = \"{db_name}\"\n  instance = google_sql_database_instance.openhack.name\n}}\n\nresource \"google_sql_user\" \"openhack\" {{\n  name     = \"{db_user}\"\n  instance = google_sql_database_instance.openhack.name\n  password = \"{db_pass}\"\n}}\n\n",
        db_name = app.db_name,
        db_user = app.db_username,
        db_pass = app.db_password
    ));

    out.push_str("# GCS — Media Storage\n");
    out.push_str("resource \"google_storage_bucket\" \"media\" {\n  name     = \"openhack-media\"\n  location = \"US\"\n  uniform_bucket_level_access = true\n}\n\n");

    out.push_str("# Pub/Sub — Inter-service Events\n");
    out.push_str(
        "resource \"google_pubsub_topic\" \"events\" {\n  name = \"openhack-events\"\n}\n\n",
    );

    if app.is_service_enabled(ServiceName::Ai) {
        out.push_str("# Secret Manager — AI API Key\n");
        out.push_str(&format!(
            "resource \"google_secret_manager_secret\" \"openai_api_key\" {{\n  secret_id = \"openai-api-key\"\n  replication {{\n    automatic = true\n  }}\n}}\n\nresource \"google_secret_manager_secret_version\" \"openai_api_key\" {{\n  secret      = google_secret_manager_secret.openai_api_key.id\n  secret_data = \"{key}\"\n}}\n\n",
            key = app.openai_api_key
        ));
    }

    out.push_str("# Cloud Run service definitions\n");
    for &svc in &app.enabled_services {
        let name = svc.docker_name();
        let port = svc.port();
        out.push_str(&format!(
            "resource \"google_cloud_run_service\" \"{name}\" {{\n  name     = \"{name}\"\n  location = \"{region}\"\n  template {{\n    spec {{\n      containers {{\n        image = \"gcr.io/{project}/{name}:latest\"\n        ports {{\n          container_port = {port}\n        }}\n        env {{\n          name  = \"DATABASE_URL\"\n          value = \"postgresql://{db_user}:{db_pass}@/openhack?host=/cloudsql/$PROJECT_ID:$REGION:$(google_sql_database_instance.openhack.connection_name)\"\n        }}\n        env {{\n          name  = \"REDIS_URL\"\n          value = \"{redis_url}\"\n        }}\n        env {{\n          name  = \"RUST_LOG\"\n          value = \"info\"\n        }}\n        env {{\n          name  = \"ENVIRONMENT\"\n          value = \"{env}\"\n        }}\n      }}\n    }}\n  }}\n  traffic {{\n    percent         = 100\n    latest_revision = true\n  }}\n}}\n\nresource \"google_cloud_run_service_iam_member\" \"{name}_public\" {{\n  service = google_cloud_run_service.{name}.name\n  location = google_cloud_run_service.{name}.location\n  role     = \"roles/run.invoker\"\n  member   = \"allUsers\"\n}}\n\n",
            name = name,
            region = app.gcp_region,
            project = app.gcp_project_id,
            port = port,
            db_user = app.db_username,
            db_pass = app.db_password,
            redis_url = app.redis_url,
            env = app.environment
        ));
    }

    out.push_str("# Outputs\n");
    out.push_str("output \"cloud_sql_instance_name\" {\n  value = google_sql_database_instance.openhack.connection_name\n}\n\n");
    out.push_str("output \"media_bucket\" {\n  value = google_storage_bucket.media.name\n}\n\n");

    fs::write(dir.join("main.tf"), out)?;
    Ok(())
}
