use crate::app::{App, ServiceName};
use std::io::Write;
use std::path::Path;

/// Generate a Helm values override file for Kubernetes deployment.
///
/// # Expected Behavior
///
/// Writes `deploy/helm/openhack/values-override.yaml` with service-specific
/// overrides derived from the `App` configuration: image tags, replica counts,
/// secrets, database connection, storage provider, and ingress hostname.
/// Only enabled services are included in the override. Disabled services
/// are omitted, relying on the chart's default values.
///
/// # Errors
///
/// Returns an error if the output file cannot be created or written.
///
/// # Side Effects
///
/// - Creates parent directories if they do not exist.
/// - Writes a YAML file to disk.
pub fn generate(app: &App, output_dir: &Path) -> Result<(), Box<dyn std::error::Error>> {
    let helm_dir = output_dir.join("deploy").join("helm").join("openhack");
    std::fs::create_dir_all(&helm_dir)?;
    let path = helm_dir.join("values-override.yaml");
    let mut f = std::fs::File::create(&path)?;

    writeln!(f, "# Auto-generated Helm values override")?;
    writeln!(f, "# Generated by openhack CLI — do not edit manually")?;
    writeln!(f)?;

    writeln!(f, "global:")?;
    writeln!(f, "  imageRegistry: \"\"")?;
    writeln!(f)?;

    writeln!(f, "postgresql:")?;
    writeln!(f, "  auth:")?;
    writeln!(f, "    username: {}", app.db_username)?;
    writeln!(f, "    database: {}", app.db_name)?;
    if !app.db_password.is_empty() {
        writeln!(f, "    password: \"{}\"", escape_yaml(&app.db_password))?;
    }
    writeln!(f)?;

    writeln!(f, "secrets:")?;
    writeln!(f, "  jwtSecret: \"{}\"", escape_yaml(&app.jwt_secret))?;
    writeln!(
        f,
        "  databasePassword: \"{}\"",
        escape_yaml(&app.db_password)
    )?;
    writeln!(f)?;

    if !app.domain_name.is_empty() {
        writeln!(f, "ingress:")?;
        writeln!(f, "  hosts:")?;
        writeln!(f, "    - host: {}", app.domain_name)?;
        writeln!(f, "      paths:")?;
        writeln!(f, "        - path: /")?;
        writeln!(f, "          pathType: Prefix")?;
        writeln!(f)?;
    }

    for svc in &app.enabled_services {
        write_service_overrides(&mut f, *svc, app)?;
    }

    writeln!(f, "monitoring:")?;
    writeln!(f, "  enabled: {}", app.prometheus_enabled)?;

    Ok(())
}

fn write_service_overrides(
    f: &mut std::fs::File,
    svc: ServiceName,
    app: &App,
) -> Result<(), Box<dyn std::error::Error>> {
    let key = service_key(svc);
    let port = svc.port();
    let docker_name = svc.docker_name();
    let tag = &app.ecr_image_tag;

    writeln!(f, "{}:", key)?;
    writeln!(f, "  image:")?;
    writeln!(f, "    repository: openhack/{}", docker_name)?;
    writeln!(f, "    tag: {}", tag)?;
    writeln!(f, "  port: {}", port)?;

    match svc {
        ServiceName::Auth => {
            writeln!(f, "  config:")?;
            writeln!(f, "    jwtSecret: \"{}\"", escape_yaml(&app.jwt_secret))?;
            writeln!(f, "    jwtExpiry: \"{}\"", app.jwt_expiry)?;
            writeln!(
                f,
                "    refreshTokenExpiry: \"{}\"",
                app.refresh_token_expiry
            )?;
            if app.github_enabled {
                writeln!(f, "    oauth:")?;
                writeln!(f, "      github:")?;
                writeln!(
                    f,
                    "        clientId: \"{}\"",
                    escape_yaml(&app.github_client_id)
                )?;
                writeln!(
                    f,
                    "        clientSecret: \"{}\"",
                    escape_yaml(&app.github_client_secret)
                )?;
            }
        }
        ServiceName::Mail => {
            writeln!(f, "  config:")?;
            writeln!(f, "    smtp:")?;
            writeln!(f, "      host: \"{}\"", escape_yaml(&app.smtp_host))?;
            writeln!(f, "      port: {}", app.smtp_port)?;
        }
        ServiceName::Ai => {
            writeln!(f, "  config:")?;
            writeln!(f, "    llmProvider: \"{}\"", app.ai_provider)?;
            if !app.openai_api_key.is_empty() {
                writeln!(
                    f,
                    "    openaiApiKey: \"{}\"",
                    escape_yaml(&app.openai_api_key)
                )?;
            }
        }
        ServiceName::Media => {
            writeln!(f, "  storage:")?;
            writeln!(f, "    provider: \"{}\"", app.storage_provider)?;
            if app.storage_provider == "s3" {
                writeln!(f, "    s3:")?;
                writeln!(f, "      bucket: \"{}\"", escape_yaml(&app.aws_s3_bucket))?;
            }
        }
        _ => {}
    }

    Ok(())
}

fn service_key(svc: ServiceName) -> &'static str {
    match svc {
        ServiceName::Auth => "authService",
        ServiceName::Core => "coreService",
        ServiceName::Gateway => "gateway",
        ServiceName::Judging => "judgingService",
        ServiceName::Leaderboard => "leaderboardService",
        ServiceName::Mail => "mailService",
        ServiceName::Notify => "notifyService",
        ServiceName::Ai => "aiService",
        ServiceName::Analytics => "analyticsService",
        ServiceName::Sponsors => "sponsorsService",
        ServiceName::Media => "mediaService",
        ServiceName::DiscordBot => "discordBotService",
    }
}

fn escape_yaml(s: &str) -> String {
    if s.contains('"') || s.contains('\\') || s.contains('\n') {
        s.replace('\\', "\\\\").replace('"', "\\\"")
    } else {
        s.to_string()
    }
}
