use crate::app::App;
use std::fs;
use std::path::Path;

pub fn generate(app: &App, output_dir: &Path) -> Result<(), Box<dyn std::error::Error>> {
    let tfvars_dir = output_dir.join("infra").join("terraform").join("envs");
    fs::create_dir_all(&tfvars_dir)?;

    let mut out = String::new();
    out.push_str("# auto-generated.tfvars — Generated by openhack-cli\n");
    out.push_str("# Review and update before running: terraform apply -var-file=envs/auto-generated.tfvars\n\n");

    out.push_str(&format!(
        "aws_region                = \"{}\"\n",
        app.aws_region
    ));
    out.push_str(&format!(
        "environment               = \"{}\"\n",
        app.environment
    ));
    out.push_str(&format!(
        "project_name              = \"{}\"\n",
        app.docker_compose_project_name
    ));
    out.push('\n');

    out.push_str("# Database\n");
    out.push_str(&format!(
        "db_username               = \"{}\"\n",
        app.db_username
    ));
    out.push_str(&format!(
        "db_password               = \"{}\"\n",
        app.db_password
    ));
    out.push_str(&format!(
        "db_name                   = \"{}\"\n",
        app.db_name
    ));
    out.push_str(&format!(
        "db_instance_class         = \"{}\"\n",
        app.db_instance_class
    ));
    out.push_str(&format!(
        "db_serverless_min_capacity = {}\n",
        app.db_serverless_min_capacity
    ));
    out.push_str(&format!(
        "db_serverless_max_capacity = {}\n",
        app.db_serverless_max_capacity
    ));
    out.push('\n');

    out.push_str("# Secrets\n");
    out.push_str(&format!(
        "jwt_secret                = \"{}\"\n",
        app.jwt_secret
    ));
    out.push_str(&format!(
        "openai_api_key            = \"{}\"\n",
        app.openai_api_key
    ));
    out.push_str(&format!(
        "discord_webhook_url       = \"{}\"\n",
        app.discord_bot_token
    ));
    out.push('\n');

    out.push_str("# Redis (empty = disabled, services degrade gracefully)\n");
    out.push_str(&format!(
        "redis_url                 = \"{}\"\n",
        if app.uses_redis() {
            app.redis_url.clone()
        } else {
            String::new()
        }
    ));
    out.push('\n');

    out.push_str("# Lambda\n");
    out.push_str(&format!(
        "lambda_memory_size        = {}\n",
        app.lambda_memory_size
    ));
    out.push_str(&format!(
        "lambda_timeout            = {}\n",
        app.lambda_timeout
    ));
    out.push('\n');

    out.push_str("# ECR\n");
    out.push_str(&format!(
        "ecr_image_tag             = \"{}\"\n",
        app.ecr_image_tag
    ));
    out.push('\n');

    out.push_str("# Custom domain (optional)\n");
    if app.domain_name.is_empty() {
        out.push_str("# domain_name              = \"\"\n");
        out.push_str("# certificate_arn          = \"\"\n");
    } else {
        out.push_str(&format!(
            "domain_name              = \"{}\"\n",
            app.domain_name
        ));
        out.push_str(&format!(
            "certificate_arn          = \"{}\"\n",
            app.certificate_arn
        ));
    }

    let tfvars_path = tfvars_dir.join("auto-generated.tfvars");
    fs::write(&tfvars_path, out)?;
    Ok(())
}
