"use client";

import { useState } from "react";
import { useAuth } from "@/contexts/auth-context";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Download, Award, Trophy, Users } from "lucide-react";
import { useToast } from "@/hooks/use-toast";

export default function CertificatePage() {
  const { user } = useAuth();
  const { toast } = useToast();
  const [generating, setGenerating] = useState(false);

  async function downloadCertificate(type: string) {
    setGenerating(true);
    try {
      const response = await fetch(`/api/analytics/certificates/${type}/${user?.id}`, {
        headers: {
          Authorization: `Bearer ${localStorage.getItem('access_token')}`,
        },
      });

      if (!response.ok) {
        throw new Error("Failed to generate certificate");
      }

      // Download PDF
      const blob = await response.blob();
      const url = window.URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `${type}_certificate.pdf`;
      link.click();
      window.URL.revokeObjectURL(url);

      toast({ title: "Certificate downloaded!" });
    } catch (error) {
      console.error("Failed to download certificate:", error);
      toast({ title: "Failed to download certificate", variant: "destructive" });
    } finally {
      setGenerating(false);
    }
  }

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-bold">Certificates</h1>
        <p className="text-muted-foreground">
          Download your hackathon certificates
        </p>
      </div>

      {/* Participation Certificate */}
      <Card>
        <CardHeader>
          <div className="flex items-center gap-2">
            <Award className="w-6 h-6 text-primary" />
            <CardTitle>Certificate of Participation</CardTitle>
          </div>
          <CardDescription>
            Recognize your participation in the hackathon
          </CardDescription>
        </CardHeader>
        <CardContent>
          <p className="text-sm text-muted-foreground mb-4">
            This certificate acknowledges your participation and contribution to the hackathon.
          </p>
          <Button
            onClick={() => downloadCertificate("participant")}
            disabled={generating}
          >
            <Download className="w-4 h-4 mr-2" />
            {generating ? "Generating..." : "Download Certificate"}
          </Button>
        </CardContent>
      </Card>

      {/* Winner Certificate (if applicable) */}
      <Card>
        <CardHeader>
          <div className="flex items-center gap-2">
            <Trophy className="w-6 h-6 text-yellow-500" />
            <CardTitle>Winner Certificate</CardTitle>
          </div>
          <CardDescription>
            For competition winners and place holders
          </CardDescription>
        </CardHeader>
        <CardContent>
          <p className="text-sm text-muted-foreground mb-4">
            If your team won a prize, download your winner certificate here.
          </p>
          <div className="text-sm text-muted-foreground">
            Winner certificates are generated by admins after the competition ends.
            Contact the organizers if you believe you should have received one.
          </div>
        </CardContent>
      </Card>

      {/* Judge Certificate (if applicable) */}
      <Card>
        <CardHeader>
          <div className="flex items-center gap-2">
            <Users className="w-6 h-6 text-blue-500" />
            <CardTitle>Judge Appreciation Certificate</CardTitle>
          </div>
          <CardDescription>
            Thank you for serving as a judge
          </CardDescription>
        </CardHeader>
        <CardContent>
          <p className="text-sm text-muted-foreground mb-4">
            Recognize your valuable contribution as a hackathon judge.
          </p>
          <div className="text-sm text-muted-foreground">
            Judge certificates are available for all judges who completed their evaluations.
          </div>
        </CardContent>
      </Card>

      {/* Info */}
      <Card>
        <CardHeader>
          <CardTitle>About Certificates</CardTitle>
        </CardHeader>
        <CardContent className="space-y-2 text-sm">
          <p>
            Certificates are provided in PDF format and can be downloaded at any time.
          </p>
          <ul className="list-disc list-inside space-y-1 text-muted-foreground">
            <li>Participation certificates are available to all registered participants</li>
            <li>Winner certificates are generated for prize-winning teams</li>
            <li>Judge certificates are available for all active judges</li>
            <li>Certificates include your name, hackathon name, and date</li>
          </ul>
        </CardContent>
      </Card>
    </div>
  );
}
